image: python:3.13

pipelines:
    branches:
        master:
            - step:
                  script:
                      - git add .                 
                      - git commit -m "update code"
                      - git push --all --force git@github.com:javishome/youtube-assistant.git