image: ubuntu:24.04 

pipelines:
    branches:
        master:
            - step:
                  script:
                    - mkdir -p ~/.ssh
                    - echo ${SSH_PRIVATE_KEY} > ~/.ssh/id_rsa
                    - chmod 600 ~/.ssh/id_rsa
                    - ssh-keyscan github.com bitbucket.org >> ~/.ssh/known_hosts
                    - ls -la
                    - ssh -T git@github.com
                    - git push --all git@github.com:javishome/youtube_assistant_addon.git
                    - rm -rf ./music_server
                    - git add .                 
                    - git commit -m "update code"
                    - git push --all --force git@github.com:javishome/youtube-assistant.git
        dev:
            - step:
                  script:
                    - apt-get update && apt-get install -y git openssh-client
                    - mkdir -p ~/.ssh
                    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                    - chmod 600 ~/.ssh/id_rsa
                    - ssh-keyscan github.com bitbucket.org >> ~/.ssh/known_hosts
                    - export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no"
                    - ls -la
                    - git remote -v
                    # - ssh -T git@github.com
                    - git clone git@github.com:javishome/youtube_assistant_addon.git
                    - ls -la
                    # - rm -rf ./music_server
                    # - git add .                 
                    # - git commit -m "update code"
                    # - git push --all --force git@github.com:javishome/youtube-assistant.git
                    