pipelines:
  branches:
    master:
      - step:
          name: Run get_repo_info script
          caches:
            - pip
          script:
              - git clone https://github.com/javishome/youtube-assistant.git
              - rm -rf youtube-assistant/custome_components/youtube_assistant/
              - cp -rf component/youtube_assistant youtube-assistant/custome_components/
              - cd youtube-assistant 
              - git add .
              - git commit -m "Update youtube_assistant"
              - git push --all git@github.com:javishome/youtube-assistant.git