pipelines:
  branches:
    master:
      - step:
          name: Run get_repo_info script
          caches:
            - pip
          script:
              - git clone git@github.com:javishome/youtube-assistant.git
              - git pull;
              - rm -rf youtube-assistant/custome_components/youtube_assistant/
              - cp -rf components/youtube_assistant/ youtube-assistant/custome_components/youtube_assistant/
              - cd youtube-assistant
              - git add .
              - git commit -m "Update youtube_assistant"
              - git push origin main